// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EventsDBConnector.Models
{
    public partial class Clubs
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public int CurrentLeague { get; set; }

        public virtual Leagues CurrentLeagueNavigation { get; set; }
    }
}