// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EventsDBConnector.Models
{
    public partial class Leagues
    {
        public Leagues()
        {
            Clubs = new HashSet<Clubs>();
            InversePromotesToNavigation = new HashSet<Leagues>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int SportId { get; set; }
        public int? PromotesTo { get; set; }

        public virtual Leagues PromotesToNavigation { get; set; }
        public virtual Sports Sport { get; set; }
        public virtual ICollection<Clubs> Clubs { get; set; }
        public virtual ICollection<Leagues> InversePromotesToNavigation { get; set; }
    }
}