// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EventsDBConnector.Models
{
    public partial class Sports
    {
        public Sports()
        {
            Leagues = new HashSet<Leagues>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<Leagues> Leagues { get; set; }
    }
}